version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb

  spring-boot-webflux-app:
    image: spring-boot-webflux-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - /data/spring-boot-webflux-app